---
version: '3.5'
services:
  molecule:
    image: quay.io/ansible/molecule:2.22
    tty: true
    volumes:
      - ${MOLECULE_PROJECT_DIR}:/molecule/${MOLECULE_ROLE_NAME}
      - /var/run/docker.sock:/var/run/docker.sock
      - ./requirements.txt:/etc/pip/requirements.txt
    working_dir: /molecule/${MOLECULE_ROLE_NAME}
    command: /bin/ash -c '[ ! -f /etc/pip/requirements.txt ] || pip install -r /etc/pip/requirements.txt && /bin/ash'
    networks:
      - molecule

networks:
  molecule:
    name: molecule
