---
version: '3.5'
services:
  molecule:
    image: quay.io/ansible/molecule:2.20
    tty: true
    volumes:
      - ${MOLECULE_PROJECT_DIR}:/molecule
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /molecule
    entrypoint: /bin/ash
    networks:
      - molecule

networks:
  molecule:
    name: molecule
